name := "spark-word-count"
version := "1.0"
scalaVersion := "2.12.15"
libraryDependencies += "org.apache.spark" % "spark-core_2.12" % "3.2.1"
libraryDependencies += "org.apache.spark" % "spark-streaming_2.12" % "3.2.1"